In [1]:
import numpy as np

In [17]:
def getLabels(X, T):
    '''
    this function is used to label the data X according to the given threshold T
    elements less than T are labeled 0, elements greater than T are labelled 1
    '''
    return (T < X).astype(int)
    

def calculateMeans(X, Y):
    '''
    this function calculates the averages of different classes
    '''
    m1 = X[Y == 0].mean()
    m2 = X[Y == 1].mean()

    return np.array([m1, m2])


def calculateSTDs(X, Y):
    '''
    this function calculates standard deviations of different classes
    '''
    s1 = X[Y == 0].std()
    s2 = X[Y == 1].std()

    return np.array([s1, s2])


def calculateMembership(X, m, s):
    '''
    this function calculates the probability of an element belonging to class 1 or 
    class 2 according to the gaussian distribution
    '''
    m = m.reshape(1,1,-1)
    s = s.reshape(1,1,-1)
    X = X.reshape(*X.shape, 1)
    
    return (np.e ** -(((X - m) ** 2) / (2 * (s ** 2)))) / (s * ((2 * np.pi) ** (1/2)))


def classify(P):
    '''
    this function takes membership values of each element and returns the class 
    with the highest membership
    '''
    return P.argmax(axis= -1)

In [18]:
T = 50                                      # threshold T
X = np.array([                              # input array
    [12, 8 , 10, 12, 112, 114, 123, 126], 
    [14, 9 , 11, 13, 98 , 102, 104, 117], 
    [15, 12, 13, 16, 96 , 93 , 101, 106], 
    [16, 14, 14, 18, 99 , 84 , 103, 102], 
    [19, 13, 17, 17, 101, 94 , 88 , 97 ]
])

In [19]:
Y = getLabels(X, T)     # labelling the data
Y

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]])

In [20]:
m = calculateMeans(X,Y)     # calculating means
m

array([ 13.65, 103.  ])

In [21]:
s = calculateSTDs(X,Y)      # calculating standard deviations
s

array([ 2.88574081, 10.58300524])

In [26]:
P = calculateMembership(X,m,s)  # calculating gaussian membership
P = classify(P)                 # using membership values and outputting class prediction
P

array([[0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1]])